name: "Publish to Docker Hub"

on:
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/publish_74.yml"
      - "7.4/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image (default)"
        uses: docker/build-push-action@v2
        with:
          context: ./7.4/
          tags: ajardin/php:7.4
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: "Build & Publish the Docker image (Blackfire)"
        uses: docker/build-push-action@v2
        with:
          context: ./7.4/blackfire/
          tags: ajardin/php:7.4-blackfire
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: "Build & Publish the Docker image (Xdebug)"
        uses: docker/build-push-action@v2
        with:
          context: ./7.4/xdebug/
          tags: ajardin/php:7.4-xdebug
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
